spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification_group
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: dto_order.OrderDTO
    listener:
      concurrency: 3

app:
  kafka:
    consumer-topic: "sent_orders"
    consumer-partitions: 6